from __future__ import annotations

import os


def main() -> None:
    timeout_ms = int(os.getenv("E2E_ROUTER_TIMEOUT_MS", "30000"))
    max_attempts = int(os.getenv("E2E_ROUTER_MAX_ATTEMPTS", "3"))
    namespace = os.getenv("E2E_NAMESPACE", "e2e-router")
    mock_base_url = f"http://router-lb-mock.{namespace}.svc.cluster.local:8080"

    lines = [
        "router:",
        "  instance_name: e2e-aks-live-load-balancing",
        f"  timeout_ms: {timeout_ms}",
        f"  max_attempts: {max_attempts}",
        "  retryable_status_codes: [429, 500, 502, 503, 504]",
        "  health:",
        "    failure_threshold: 3",
        "    cooldown_seconds: 30",
        "    half_open_after_seconds: 60",
        "",
        "deployments:",
        "  - id: chat-active-active-80-20",
        "    kind: llm",
        "    protocol: openai_chat",
        "    routing:",
        "      strategy: tiered_failover",
        "    limits:",
        "      max_concurrency: 10",
        "      request_rate_per_second: 10",
        "    upstreams:",
        "      - id: chat-a",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-a",
        "        tier: 0",
        "        weight: 100",
        "        model_name: gpt-4.1",
        "        model_version: 2025-04-14",
        "        deployment_name: mock-chat-a",
        "        compatibility_group: chat-primary",
        "        target_share_percent: 80",
        "        max_share_percent: 80",
        "        endpoint: " + mock_base_url + "/chat/a",
        "        auth:",
        "          mode: none",
        "      - id: chat-b",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-b",
        "        tier: 0",
        "        weight: 100",
        "        model_name: gpt-4.1",
        "        model_version: 2025-04-14",
        "        deployment_name: mock-chat-b",
        "        compatibility_group: chat-primary",
        "        target_share_percent: 20",
        "        max_share_percent: 20",
        "        endpoint: " + mock_base_url + "/chat/b",
        "        auth:",
        "          mode: none",
        "",
        "  - id: chat-active-standby",
        "    kind: llm",
        "    protocol: openai_chat",
        "    routing:",
        "      strategy: tiered_failover",
        "    limits:",
        "      max_concurrency: 10",
        "      request_rate_per_second: 10",
        "    upstreams:",
        "      - id: chat-primary",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-a",
        "        tier: 0",
        "        weight: 100",
        "        model_name: gpt-4.1",
        "        model_version: 2025-04-14",
        "        deployment_name: mock-chat-primary",
        "        compatibility_group: chat-controlled",
        "        balancing_policy: active_standby",
        "        endpoint: " + mock_base_url + "/chat/primary",
        "        auth:",
        "          mode: none",
        "      - id: chat-standby",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-b",
        "        tier: 0",
        "        weight: 100",
        "        model_name: gpt-4.1",
        "        model_version: 2025-04-14",
        "        deployment_name: mock-chat-standby",
        "        compatibility_group: chat-controlled",
        "        balancing_policy: active_standby",
        "        warm_standby: true",
        "        endpoint: " + mock_base_url + "/chat/standby",
        "        auth:",
        "          mode: none",
        "",
        "  - id: chat-active-standby-failover",
        "    kind: llm",
        "    protocol: openai_chat",
        "    routing:",
        "      strategy: tiered_failover",
        "    limits:",
        "      max_concurrency: 10",
        "      request_rate_per_second: 10",
        "    upstreams:",
        "      - id: chat-primary-fail",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-a",
        "        tier: 0",
        "        weight: 100",
        "        model_name: gpt-4.1",
        "        model_version: 2025-04-14",
        "        deployment_name: mock-chat-primary-fail",
        "        compatibility_group: chat-controlled-failover",
        "        balancing_policy: active_standby",
        "        endpoint: " + mock_base_url + "/chat/fail",
        "        auth:",
        "          mode: none",
        "      - id: chat-standby-failover",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-b",
        "        tier: 0",
        "        weight: 100",
        "        model_name: gpt-4.1",
        "        model_version: 2025-04-14",
        "        deployment_name: mock-chat-standby",
        "        compatibility_group: chat-controlled-failover",
        "        balancing_policy: active_standby",
        "        warm_standby: true",
        "        endpoint: " + mock_base_url + "/chat/standby",
        "        auth:",
        "          mode: none",
        "",
        "  - id: embeddings-active-active-80-20",
        "    kind: embeddings",
        "    protocol: openai_embeddings",
        "    routing:",
        "      strategy: tiered_failover",
        "    limits:",
        "      max_concurrency: 10",
        "      request_rate_per_second: 10",
        "    upstreams:",
        "      - id: emb-a",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-a",
        "        tier: 0",
        "        weight: 100",
        "        model_name: text-embedding-3-small",
        "        model_version: '1'",
        "        deployment_name: mock-emb-a",
        "        compatibility_group: embeddings-primary",
        "        target_share_percent: 80",
        "        max_share_percent: 80",
        "        endpoint: " + mock_base_url + "/embeddings/a",
        "        auth:",
        "          mode: none",
        "      - id: emb-b",
        "        provider: internal_mock",
        "        account: live-lb",
        "        region: local-b",
        "        tier: 0",
        "        weight: 100",
        "        model_name: text-embedding-3-small",
        "        model_version: '1'",
        "        deployment_name: mock-emb-b",
        "        compatibility_group: embeddings-primary",
        "        target_share_percent: 20",
        "        max_share_percent: 20",
        "        endpoint: " + mock_base_url + "/embeddings/b",
        "        auth:",
        "          mode: none",
        "",
        "shared_services: {}",
    ]

    print("\n".join(lines))


if __name__ == "__main__":
    main()
