apiVersion: v1
kind: Service
metadata:
  name: router-failover-mock
spec:
  selector:
    app: router-failover-mock
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
