apiVersion: apps/v1
kind: Deployment
metadata:
  name: router-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: router-redis
  template:
    metadata:
      labels:
        app: router-redis
    spec:
      containers:
        - name: redis
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 10
